server:
  port: 8000

spring:
  redis:
    host: 192.168.47.101
    port: 6379
    password: root
    database: 1

  session:
    store-type: redis  #session存储方式
    timeout: 1800      #session过期时间 单位：秒

